version: "3.8"

services:
  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    volumes:
      - ./go:/app
    networks:
      - backend
    ports:
      - 8081:8081

  node:
    image: mcr.microsoft.com/playwright:focal
    working_dir: /usr/app
    command: sh -c "yarn && yarn watch"
    user: "1000"
    volumes:
      - ./node:/usr/app
    networks:
      - backend
    ports:
      - 8080:8080

networks:
  backend:
